In [1]:
import pandas as pd
import numpy as np

facebook_ads = pd.read_csv('../data/marketing/Facebook Ads.csv')
facebook_ads.head()

,Ad name,Delivery status,Delivery level,Reach,Impressions,Frequency,Result type,Results,Amount spent (THB),Cost per result,Starts,Ends,Rest ID,Rest 2,Rest 3,Rest 4,Rest 5
0,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,156467,332013,2.121936,Website purchases,689,7396.81,10.735573,20/03/2025,NaN,4503,837.0,NaN,NaN,NaN
1,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,78081,167712,2.147923,Website purchases,340,5438.39,15.995265,20/03/2025,NaN,4503,837.0,NaN,NaN,NaN
2,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,56111,85464,1.523124,Website purchases,191,2230.25,11.676702,20/03/2025,NaN,4503,837.0,NaN,NaN,NaN
3,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,37510,66331,1.768355,Website purchases,117,2158.46,18.448376,20/03/2025,NaN,4503,837.0,NaN,NaN,NaN
4,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,4327,5107,1.180263,Website purchases,3,224.04,74.680000,20/03/2025,NaN,4503,837.0,NaN,NaN,NaN

In [2]:
facebook_ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3987 entries, 0 to 3986
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ad name             3987 non-null   object
 1   Delivery status     3987 non-null   object
 2   Delivery level      3987 non-null   object
 3   Reach               3987 non-null   int64
 4   Impressions         3987 non-null   int64
 5   Frequency           3987 non-null   float64
 6   Result type         3191 non-null   object
 7   Results             3182 non-null   object
 8   Amount spent (THB)  3987 non-null   float64
 9   Cost per result     3191 non-null   float64
 10  Starts              3987 non-null   object
 11  Ends                1816 non-null   object
 12  Rest ID             3432 non-null   object
 13  Rest 2              43 non-null     float64
 14  Rest 3              6 non-null      float64
 15  Rest 4              1 non-null      float64
 16  Rest 5              1 non-null      float64
dtypes: float64(7), int64(2), object(8)
memory usage: 529.7+ KB

In [3]:
# 2. Extract and Split the 'Ad name' column
def parse_ad_name(ad_name):
    parsed = {}
    # Check if the row follows the structured Key=Value format
    if isinstance(ad_name, str) and '|' in ad_name and '=' in ad_name:
        parts = ad_name.split('|')
        for part in parts:
            if '=' in part:
                key, value = part.split('=', 1)
                parsed[key] = value.strip()
    return parsed

# Apply the parsing function and expand into new columns
extracted_features = facebook_ads['Ad name'].apply(parse_ad_name).apply(pd.Series)

In [4]:
# Merge the new features back into the main DataFrame
facebook_ads = pd.concat([facebook_ads, extracted_features], axis=1)
facebook_ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3987 entries, 0 to 3986
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ad name             3987 non-null   object
 1   Delivery status     3987 non-null   object
 2   Delivery level      3987 non-null   object
 3   Reach               3987 non-null   int64
 4   Impressions         3987 non-null   int64
 5   Frequency           3987 non-null   float64
 6   Result type         3191 non-null   object
 7   Results             3182 non-null   object
 8   Amount spent (THB)  3987 non-null   float64
 9   Cost per result     3191 non-null   float64
 10  Starts              3987 non-null   object
 11  Ends                1816 non-null   object
 12  Rest ID             3432 non-null   object
 13  Rest 2              43 non-null     float64
 14  Rest 3              6 non-null      float64
 15  Rest 4              1 non-null      float64
 16  Rest 5              1 non-null      float64
 17  SRC                 366 non-null    object
 18  COUNTRY             270 non-null    object
 19  RID                 366 non-null    object
 20  RNAME               366 non-null    object
 21  TYPE                269 non-null    object
 22  CAMP                111 non-null    object
 23  KOLID               133 non-null    object
 24  PLAT                366 non-null    object
 25  DATE                328 non-null    object
dtypes: float64(7), int64(2), object(17)
memory usage: 810.0+ KB

In [5]:
facebook_ads.head()

,Ad name,Delivery status,Delivery level,Reach,Impressions,Frequency,Result type,Results,Amount spent (THB),Cost per result,...,Rest 5,SRC,COUNTRY,RID,RNAME,TYPE,CAMP,KOLID,PLAT,DATE
0,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,156467,332013,2.121936,Website purchases,689,7396.81,10.735573,...,NaN,KOL,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-PLS,FB,2025-12-03
1,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,78081,167712,2.147923,Website purchases,340,5438.39,15.995265,...,NaN,KOL,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-KJK,FB,2025-12-04
2,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,56111,85464,1.523124,Website purchases,191,2230.25,11.676702,...,NaN,KOL,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-PLS,FB,2025-12-03
3,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,37510,66331,1.768355,Website purchases,117,2158.46,18.448376,...,NaN,KOL,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-KJK,FB,2025-12-04
4,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,4327,5107,1.180263,Website purchases,3,224.04,74.680000,...,NaN,KOL,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER BEYOND BUFFET CAMPAIGN,HH-CTH,FB,2025-12-15

In [6]:
# facebook_ads[['Rest ID ', 'RID']].head()
# facebook_ads.columns
# Create a dictionary with the old names as keys and the new names as values
rename_mapping = {
    'SRC': 'Source',
    'RID': 'Restaurant_ID_frm_adtext',
    'RNAME': 'Restaurant Name',
    'CAMP': 'Campaign',
    'KOLID': 'KOL_ID',
    'PLAT': 'Platform'
}

facebook_ads = facebook_ads.rename(columns=rename_mapping)
facebook_ads.columns

Index(['Ad name', 'Delivery status', 'Delivery level', 'Reach', 'Impressions',
       'Frequency', 'Result type', 'Results', 'Amount spent (THB)',
       'Cost per result', 'Starts', 'Ends', 'Rest ID ', 'Rest 2', 'Rest 3',
       'Rest 4', 'Rest 5', 'Source', 'COUNTRY', 'Restaurant_ID_frm_adtext',
       'Restaurant Name', 'TYPE', 'Campaign', 'KOL_ID', 'Platform', 'DATE'],
      dtype='object')

In [7]:
# 3. Process Timestamps
# Convert main start and end dates
facebook_ads['Start_Date'] = pd.to_datetime(facebook_ads['Starts'], errors='coerce')
facebook_ads['End_Date'] = pd.to_datetime(facebook_ads['Ends'], errors='coerce')
# Clean and convert the extracted 'DATE' column (removing accidental appended strings)
if 'DATE' in facebook_ads.columns:
    facebook_ads['DATE'] = facebook_ads['DATE'].astype(str).str.replace(' - Copy', '', regex=False)
    facebook_ads['DATE'] = pd.to_datetime(facebook_ads['DATE'], errors='coerce')
# We use drop() with axis=1 (or columns=[...]) to remove them entirely
facebook_ads = facebook_ads.drop(columns=['Starts', 'Ends'], errors='ignore')

C:\Users\foogu\AppData\Local\Temp\ipykernel_16080\1730411335.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  facebook_ads['Start_Date'] = pd.to_datetime(facebook_ads['Starts'], errors='coerce')
C:\Users\foogu\AppData\Local\Temp\ipykernel_16080\1730411335.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  facebook_ads['End_Date'] = pd.to_datetime(facebook_ads['Ends'], errors='coerce')

In [28]:
facebook_ads.head()

,Ad name,Delivery status,Delivery level,Reach,Impressions,Frequency,Result type,Results,Amount spent (THB),Cost per result,...,COUNTRY,Restaurant_ID_frm_adtext,Restaurant Name,TYPE,Campaign,KOL_ID,Platform,DATE,Start_Date,End_Date
0,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,156467,332013,2.121936,Website purchases,689,7396.81,10.735573,...,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-PLS,FB,2025-12-03,2025-03-20,NaT
1,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,78081,167712,2.147923,Website purchases,340,5438.39,15.995265,...,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-KJK,FB,2025-12-04,2025-03-20,NaT
2,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,56111,85464,1.523124,Website purchases,191,2230.25,11.676702,...,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-PLS,FB,2025-12-03,2025-03-20,NaT
3,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,37510,66331,1.768355,Website purchases,117,2158.46,18.448376,...,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER CAMPAIGN,HH-KJK,FB,2025-12-04,2025-03-20,NaT
4,SRC=KOL|COUNTRY=TH|RID=4503+837|RNAME=COPPER_B...,active,ad,4327,5107,1.180263,Website purchases,3,224.04,74.680000,...,TH,4503+837,COPPER_BEYOND_BUFFET,IMG,COPPER BEYOND BUFFET CAMPAIGN,HH-CTH,FB,2025-12-15,2025-03-20,NaT

In [9]:
# 1. Define the reference date for active campaigns (e.g., today)
# Alternatively, if you know the exact date you pulled this data, use that (e.g., pd.to_datetime('2025-12-31'))
reference_date = pd.Timestamp.now() 

# 2. Calculate duration by temporarily filling NaT with the reference date
facebook_ads['Campaign Duration (Days)'] = (facebook_ads['End_Date'].fillna(reference_date) - facebook_ads['Start_Date']).dt.days

In [11]:
facebook_ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3987 entries, 0 to 3986
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Ad name                   3987 non-null   object
 1   Delivery status           3987 non-null   object
 2   Delivery level            3987 non-null   object
 3   Reach                     3987 non-null   int64
 4   Impressions               3987 non-null   int64
 5   Frequency                 3987 non-null   float64
 6   Result type               3191 non-null   object
 7   Results                   3182 non-null   object
 8   Amount spent (THB)        3987 non-null   float64
 9   Cost per result           3191 non-null   float64
 10  Rest ID                   3432 non-null   object
 11  Rest 2                    43 non-null     float64
 12  Rest 3                    6 non-null      float64
 13  Rest 4                    1 non-null      float64
 14  Rest 5                    1 non-null      float64
 15  Source                    366 non-null    object
 16  COUNTRY                   270 non-null    object
 17  Restaurant_ID_frm_adtext  366 non-null    object
 18  Restaurant Name           366 non-null    object
 19  TYPE                      269 non-null    object
 20  Campaign                  111 non-null    object
 21  KOL_ID                    133 non-null    object
 22  Platform                  366 non-null    object
 23  DATE                      322 non-null    datetime64[ns]
 24  Start_Date                3987 non-null   datetime64[ns]
 25  End_Date                  1816 non-null   datetime64[ns]
 26  Campaign Duration (Days)  3987 non-null   int64
dtypes: datetime64[ns](3), float64(7), int64(3), object(14)
memory usage: 841.1+ KB

In [ ]:
# 1. Define the list of outlier Restaurant IDs
outlier_ids = ['4503', '4502', '933', '837']

# 2. Join them into a single regular expression pattern separated by the OR operator (|)
# This creates the pattern: '4503|4502|933|837'
pattern = '|'.join(outlier_ids)

# 3. Filter the dataframe
# We use the tilde (~) to say "KEEP the rows that DO NOT contain this pattern"
# (Assuming you renamed the column to 'Rest ID' as discussed previously)
facebook_ads = facebook_ads[~facebook_ads['Rest ID '].astype(str).str.contains(pattern, na=False)]
facebook_ads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3559 entries, 31 to 3986
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Ad name                   3559 non-null   object
 1   Delivery status           3559 non-null   object
 2   Delivery level            3559 non-null   object
 3   Reach                     3559 non-null   int64
 4   Impressions               3559 non-null   int64
 5   Frequency                 3559 non-null   float64
 6   Result type               2818 non-null   object
 7   Results                   2809 non-null   object
 8   Amount spent (THB)        3559 non-null   float64
 9   Cost per result           2818 non-null   float64
 10  Rest ID                   3004 non-null   object
 11  Rest 2                    12 non-null     float64
 12  Rest 3                    6 non-null      float64
 13  Rest 4                    1 non-null      float64
 14  Rest 5                    1 non-null      float64
 15  Source                    335 non-null    object
 16  COUNTRY                   239 non-null    object
 17  Restaurant_ID_frm_adtext  335 non-null    object
 18  Restaurant Name           335 non-null    object
 19  TYPE                      238 non-null    object
 20  Campaign                  80 non-null     object
 21  KOL_ID                    121 non-null    object
 22  Platform                  335 non-null    object
 23  DATE                      291 non-null    datetime64[ns]
 24  Start_Date                3559 non-null   datetime64[ns]
 25  End_Date                  1736 non-null   datetime64[ns]
 26  Campaign Duration (Days)  3559 non-null   int64
dtypes: datetime64[ns](3), float64(7), int64(3), object(14)
memory usage: 778.5+ KB

In [21]:
facebook_ads['Rest ID '].value_counts()

Rest ID
~       563
2025    101
3596     64
1433     57
2536     55
       ...
608       1
1963      1
4142      1
1350      1
1622      1
Name: count, Length: 458, dtype: int64